export enum FijosMsgType {
  OPEN_BET_KEYBOARD = 'OPEN_BET_KEYBOARD',
  CLOSE_BET_KEYBOARD = 'CLOSE_BET_KEYBOARD',
  OPEN_AMOUNT_KEYBOARD = 'OPEN_AMOUNT_KEYBOARD',
  CLOSE_AMOUNT_KEYBOARD = 'CLOSE_AMOUNT_KEYBOARD',
  PROCESS_BET_INPUT = 'PROCESS_BET_INPUT',
  SUBMIT_AMOUNT_INPUT = 'SUBMIT_AMOUNT_INPUT',
  CONFIRM_APPLY_AMOUNT_ALL = 'CONFIRM_APPLY_AMOUNT_ALL',
  CONFIRM_APPLY_AMOUNT_SINGLE = 'CONFIRM_APPLY_AMOUNT_SINGLE',
  CANCEL_AMOUNT_CONFIRMATION = 'CANCEL_AMOUNT_CONFIRMATION',
}

export type FijosMsg =
  | { type: FijosMsgType.OPEN_BET_KEYBOARD }
  | { type: FijosMsgType.CLOSE_BET_KEYBOARD }
  | { type: FijosMsgType.OPEN_AMOUNT_KEYBOARD; betId: string; amountType: 'fijo' | 'corrido' }
  | { type: FijosMsgType.CLOSE_AMOUNT_KEYBOARD }
  | { type: FijosMsgType.PROCESS_BET_INPUT; inputString: string }
  | { type: FijosMsgType.SUBMIT_AMOUNT_INPUT; amountString: string }
  | { type: FijosMsgType.CONFIRM_APPLY_AMOUNT_ALL }
  | { type: FijosMsgType.CONFIRM_APPLY_AMOUNT_SINGLE }
  | { type: FijosMsgType.CANCEL_AMOUNT_CONFIRMATION };
