export const AUTH_ERROR_CODES = {
    NO_REFRESH_TOKEN: 'NO_REFRESH_TOKEN',
    TERMINAL_REFRESH_FAILURE: 'TERMINAL_REFRESH_FAILURE',
    SESSION_EXPIRED: 'SESSION_EXPIRED',
    FAILED_TO_GET_USER_PROFILE: 'FAILED_TO_GET_USER_PROFILE',
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
